# Generated by Django 5.1 on 2024-12-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_name_user_username_remove_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
